version: "3.8"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NEXTCLOUD_ADMIN_USER=fred
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=nextcloud
    volumes:
      - /disk/appdata/nextcloud/config:/config # Remplacer /disk par le moint de montage
      - /disk/appdata/nextcloud/data:/data     # Remplacer /disk par le moint de montage
    depends_on:
      - nextcloud-db
    ports:
      - 450:443
    networks:
      - gobieIO
    restart: unless-stopped
  
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: nextcloud-db
    environment:
      - PUID=998  # Change UID si besoin
      - PGID=100  # Change GID si besoin
      - TZ=Europe/Paris
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
    ports:
      - 3306:3306
    volumes:
      - /disk/appdata/nextcloud/db:/config    # Remplacer /disk par le moint de montage
    restart: unless-stopped
    
env_files:
    - ../base.env
