version: "3.8"

# nextcloud containers
services:

  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${TANK}/appdata/nextcloud/config:/config
      - ${TANK}/cloud:/data
      - ${TANK}/media:/media
      - ${TANK}/download:/download
    depends_on:
      - nextcloud-db
    networks:
      - front
    ports:
      - 450:443

  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${TANK}/appdata/nextcloud/db:/config
      
networks:
  front:
    external: true
    name: "${FRONT_NET}"
