version: "3.8"

networks:
  default:
  front:
    name: proxy

services:

  # Reverse proxy
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    env_file:
      - .env.base
      - .env.proxy
    environment:
      - URL=${DOMAIN}
    volumes:
      - ${TANK}/appdata/swag:/config
    networks:
      - front
    ports:
      - 10443:443
      
  # Mainboard
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    volumes:
      - ${TANK}/appdata/heimdall:/config
