version: "3.9"
services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    restart: unless-stopped 
    devices:
      - /dev/vchiq:/dev/vchiq
    environment:
      # - JELLYFIN_PublishedServerUrl=192.168.0.101 #optional
    volumes:
      - ${TANK}/appdata/jellyfin:/config
      - ${TANK}/media:/data/media
    networks:
      - front
    # ports:
    # - 8096:8096
  
  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    restart: unless-stopped 
    environment:
      - DELUGE_LOGLEVEL=error
    volumes:
      - ${TANK}/appdata/deluge:/config
      - ${TANK}/download:/data/download
    networks:
      - front
    ports:
    #  - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - deluge
    volumes:
      - ${TANK}/appdata/sonarr:/config
      - ${TANK}/media/videos/series:/data/series
      - ${TANK}/download:/data/download
    networks:
      - front
    # ports:
    #  - 8989:8989
 
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - deluge
    volumes:
      - ${TANK}/appdata/radarr:/config
      - ${TANK}/media/videos/films:/data/films
      - ${TANK}/download:/data/download
    #ports:
    #  - 7878:7878
  
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    depends_on:
      - deluge
    volumes:
      - ${TANK}/appdata/lidarr:/config
      - ${TANK}/media/musiques:/data/musiques
      - ${TANK}/download:/data/download
    networks:
      - front
    #ports:
    #  - 8686:8686

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - AUTO_UPDATE=true
    volumes:
      - ${TANK}/appdata/jackett:/config
    networks:
      - front
    # ports:
    #  - 9117:9117
    
networks:
  front:
    external:
      name: proxy
