version: "3.9"

# Nextcloud containers
services:

  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - REDIS_HOST=nextcloud-redis
    volumes:
      - ${TANK}/appdata/nextcloud/config:/config
      - ${TANK}/cloud:/data
      - ${TANK}/media:/media
      - ${TANK}/download:/download
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - front
    ports:
      - 450:443
    
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${TANK}/appdata/nextcloud/db:/config
      
  redis:
    image: redis:latest
    container_name: nextcloud-redis
    restart: unless-stopped
   
networks:
  front:
    name: "${FRONT_NET}"
