version: "3.8"

networks:
  front:
    name: proxy

services:

  # Reverse proxy
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    env_file:
      - .env.base
      - .env.proxy
    environment:
      - URL=${DOMAIN}
    volumes:
      - ${TANK}/appdata/swag:/config
    networks:
      - default
      - front
    ports:
      - 10443:443
  
  # Authentication and authorization    
  authelia:
    image: ghcr.io/authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    volumes:
      -  ${TANK}/appdata/authelia:/config
     
  # Mainboard
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    volumes:
      - ${TANK}/appdata/heimdall:/config
      
  # Backup    
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    restart: unless-stopped
    env_file:
      - .env.base
    volumes:
      - ${TANK}/appdata/duplicati:/config
      - ${TANK}:/source
    expose:
      - 8200

