version: "3.8"

volumes:
  cloud:
    name: ${TANK}/cloud
  media:
    external: true
  download:
    external: true
    
networks:
  front:
    name: proxy
    external: true    

# Nextcloud containers
services:

  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    env_file:
      - .env.base
      - .env.cloud
    environment:
      - REDIS_HOST=nextcloud-redis
    volumes:
      - ${TANK}/appdata/nextcloud/config:/config
      - cloud:/data
      - media:/media
      - download:/download
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - front
    ports:
      - 450:443
    
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - .env.base
      - .env.cloud
    volumes:
      - ${TANK}/appdata/nextcloud/db:/config
      
  redis:
    image: redis:latest
    container_name: nextcloud-redis
    restart: unless-stopped
